fibonacci
mwiski/Calculator pull request #2
Opened 2019-04-01 20:49 UTC by mwiski

2019-04-02 06:35 UTC, mps4dev requested changes
:-1

2019-04-02 06:35 UTC, mps4dev commented on src/main/java/com/kodilla/calculator/Calculator.java
> +            return n;
tutaj zwracamy 1.

2019-04-02 06:35 UTC, mps4dev commented on src/main/java/com/kodilla/calculator/Calculator.java
> +        return fibonacci(n - 1) + fibonacci(n - 2);
Podejście rekurencyjne jest jak najbardziej okej i w tym przypadku samo się narzuca :) ale ma jedną i to dość sporą wadę :) Czy probowałeś policzyć fibonacci(100000)?

2019-04-02 13:11 UTC, mwiski commented
Zmieniłem metodę, bo zauważyłem też już rano, że w podejściu rekurencyjnym, nie zwraca mi liczb dla wysokich wartości n i ogólnie poczytałem na ten temat :)

2019-04-03 07:42 UTC, mps4dev requested changes
Popraw inicjalizację.

2019-04-03 07:42 UTC, mps4dev commented on src/main/java/com/kodilla/calculator/Calculator.java
> +            n3 = n1 + n2;
A jaki będzie u ciebie wynik dla f(2)? Powinno być 2 :) f(0) = 1, f(1) = 1, f(2) = f(0) + f(1) = 1 + 1 = 2; Moim zdaniem coś nie tak z inicjalizacą n1 :)

2019-04-03 15:58 UTC, mps4dev requested changes
:-1:

2019-04-03 15:58 UTC, mps4dev commented on src/main/java/com/kodilla/calculator/Calculator.java
> +        for (int i = 0; i < n; i++){
tu raczej nie powinno być zmiany, a raczej w linijce poprzedniej :) n1 = 1;

2019-04-04 13:16 UTC, mps4dev approved these changes
:+1:

2019-04-04 13:16 UTC, mps4dev commented
Możesz teraz zmerdżować do mastera brancza fibonacci i usunąć go zarówno lokalnie jak i wzdalnym repozytorium :) Zmerdżuj przy użyciu "squash"

2019-04-04 14:08 UTC, merged